name: Garden Weather Alert

on:
  schedule:
    - cron: "0 10 * * *" # Run daily at 10:00 AM UTC
  workflow_dispatch: # Allow manual manual triggering

permissions:
  issues: write  # Permission to create and manage issues
  contents: read # Permission to read repository contents

jobs:
  weather_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run weather-alert.js
        env:
          API_KEY: ${{ secrets.ACCUWEATHER_API_KEY }} # Your weather API key stored as a repository secret
          LOCATION: ${{ secrets.LOCATION_KEY }} # Your location stored as a repository secret
        run: node weather-alert.js
